#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

new_string="listen 80 default_server;\nlisten [::]:80 default_server;\nlocation /redirect_me {\nrewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"
sudo sed -i "s/listen 80 default_server;\nlisten [::]:80 default_server;/$new_string/" /etc/nginx/sites-available/default
sudo service nginx restart
