#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

new_string="listen 80 default_server;\nlisten [::]:80 default_server;\nrewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4;\nreturn 301;"
sed -i "s/listen 80 default_server;\nlisten [::]:80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
