#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page

echo "Ceci n'est pas une page" > /var/www/html/404.html
new_string="listen 80 default_server;\nlisten [::]:80 default_server;\nerror_page 404 /404.html;"
sed -i "s/listen 80 default_server;\nlisten [::]:80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
