#!/usr/bin/env bash
#configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt -y update
sudo apt -y install nginx

sudo chmod 777 /var/www/html/index.nginx-debian.html 
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/404.html
sudo chmod 777 /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

sudo sed -i 'error_page 404 /404.html;' /etc/nginx/sites-enabled/default

sudo sed -i "/location / {/a add_header X-Served-By: '$HOSTNAME';" /etc/nginx/sites-enabled/default

sudo service nginx restart