#!/usr/bin/env bash
#Write a Bash script that generates
#a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -u root -p$1 --all-databases --master-data > backup.sql
ddate=`date +"%d-%m-%Y"`
sudo gzip backup.sql > $ddate.tar.gz
