#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
new_string="listen 80 default_server;\nlisten [::]:80 default_server;"
sed -i "s/listen 8080 default_server;\nlisten [::]:8080 default_server;/$new_string/" /etc/nginx/sites-enabled/default
sudo service nginx restart
