#!/usr/bin/env bash
# Bash script that does things
touch /var/run/myscript.pid
while :
  do
		trap 'rm -r /var/run/myscript.pid | echo "I hate the kill command"' 15
    trap 'echo "Y U no love me?!"' 2
    trap 'rm -r /var/run/myscript.pid' 3
    echo "To infinity and beyond"
    sleep 2
  done
