#!/usr/bin/env bash
# Bash script that displays I am invincible!!!
# when receiving a SIGTERM signal
while :
  do
                trap 'echo "I am invincible!!!"' 15
    echo "To infinity and beyond"
    sleep 2
  done
