#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
counter=1
while [ $counter -lt 10 ]
do
  echo "Best School"
  counter=$((counter + 1))
  if [ $counter = 9 ]
    then 
      echo "Hi"
  fi
done
