#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user www-data;/user nginx;" /etc/nginx/nginx.conf
su nginx -c "service nginx restart"
