#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sudo service nginx restart
